# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hashes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chashes.proto\x12\x03tac\"\x16\n\x06Hashes\x12\x0c\n\x04hash\x18\x01 \x03(\t')



_HASHES = DESCRIPTOR.message_types_by_name['Hashes']
Hashes = _reflection.GeneratedProtocolMessageType('Hashes', (_message.Message,), {
  'DESCRIPTOR' : _HASHES,
  '__module__' : 'hashes_pb2'
  # @@protoc_insertion_point(class_scope:tac.Hashes)
  })
_sym_db.RegisterMessage(Hashes)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HASHES._serialized_start=21
  _HASHES._serialized_end=43
# @@protoc_insertion_point(module_scope)
